project:
  type: website
  output-dir: _site

website:
  page-navigation: true
  title: "NSIDC Data Cookbook"

  sidebar:
    title: "NSIDC Data Cookbook"
    logo: https://nsidc.org/themes/custom/nsidc/logo.svg
    pinned: true
    align: center
    tools: 
#      - icon: globe
#        href: https://nasa-openscapes.github.io
#        text: "NASA-Openscapes website"
      - icon: github
        href: https://github.com/nsidc/NSIDC-Data-Cookbook
        text: "NSIDC Data Cookbook repo"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Welcome"
        href: nsidc-data-cookbook/introduction.qmd
      - section: "How do I..."
        href: nsidc-data-cookbook/how-to-guides/overview.qmd
        contents:
          - section: "How do I reproject a netCDF file from the command line?"
          - section: "How do I reproject a netCDF file using `xarray`?"
          - section: "How do I reproject a GeoTIFF from the command line?"
          - section: "How do I reproject a GeoTIFF using rioxarray?"
          - section: "How do I find the bounding box of a grid?"
          - section: "How to I find the latitude and longitudes of grid cells?"
          
      - section: "Tutorials"
        contents:
      - section: "Reference Guides"
        href: nsidc-data-cookbook/reference-guides/overview.qmd
        contents:
          - section: "Coordinate Reference Systems"
          - href: nsidc-data-cookbook/reference-guides/coordinate_reference_systems_overview.qmd
            contents:
            - text: "What is a Coordinate Reference System?"
            - text: "Map projections and grids"
              href: nsidc-data-cookbook/reference-guides/projections.qmd
            - text: "Alls Affine!"
            - text: "Making NetCDF files CF-Compliant"
          - section: "Data Access"
            contents:
            - text: "NASA collections and granules"
            - text: "Data Formats Explained"
          - section: "Scientific Programming"
            contents:
            - text: "What is an API?"
          
      - section: "Examples"
        contents:

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true

filters:
  - include-files.lua
  - quarto

