---
title: "Data access"
---

#### **Prerequisite reminder** 

A [NASA Earthdata Login](https://urs.earthdata.nasa.gov/) is required for all data access methods, including download and direct cloud access.

#### **NASA Earthdata Cloud**

The NASA Earthdata Cloud is NASA’s cloud-based archive of Earth observation data. It is hosted by Amazon Web Services (AWS) in region us-west-2. Downloading data from the Earthdata Cloud to your local computer or storage system is and will continue to be free for users. You don't need an AWS account to download data.  Alternatively, you can work directly with NSIDC DAAC holdings stored in Amazon S3 (the object storage service used by NASA Earthdata Cloud). This direct access method allows you stream data into memory and analyze it "in place", avoiding large transfers to your local computer.

Options for accessing NASA Earthdata are outlined below:

#### **Option 1: Browser-Based Download (No Coding Required)**

If you prefer a graphical interface, use one of these web-based tools: 

[NASA Earthdata Search](https://search.earthdata.nasa.gov) - Explore, filter and customize data before downloading files. Instructions for using Earthdata Search to find and access data can be found in our Earthdata Search [guide](https://nsidc.org/data/user-resources/help-center/search-order-and-customize-nsidc-daac-data-nasa-earthdata-search). 

image

Data Access Tool - The NSIDC Data Access Tool can be accessed from a data set's landing page. 
Example: [ATLAS/ICESat-2 L2A Global Geolocated Photon Data. (ATL03, Version 7) Landing Page](https://nsidc.org/data/atl03/versions/7). In the right-hand menu on a data set landing page, click "Data Access & Tools".  You will be directed to the top of a list of tool and service "cards" with links to various data access methods.  Click on the card title "Data Access Tool" to be directed to the Data Access Tool interface for that particular data set.  The Data Access Tool allows users to filter files within a data set using spatial bounds, temporal ranges, and filename wildcards.

Help article on using the Data Access Tool: [https://nsidc.org/data/user-resources/help-center/filter-and-order-data-set-web-page-using-data-access-tool](https://nsidc.org/data/user-resources/help-center/filter-and-order-data-set-web-page-using-data-access-tool)

#### **Option 2: Python (earthaccess Library)**

The earthaccess Python library provides a streamlined way to search, authenticate, and download NASA Earthdata. It works both locally and in the cloud (e.g., on EC2 or JupyterHub environments).

earthaccess [documentation](https://earthaccess.readthedocs.io/en/stable/)

*Have reference/link to "how to guide" here?*

#### **Option 3: Command Line Tools (```wget```, ```curl```, PODAAC subscriber)**

If you're comfortable using the terminal, command-line tools allow flexible and efficient downloading. 

```wget``` or ```curl``` – Download known files or batch download from an HTTPS URL list.
Learn to create .txt files of download links here: [Creating Text Files of HTTPS and S3 URLs for Earthdata Cloud Data Access](https://nsidc.org/data/user-resources/help-center/creating-text-files-https-and-s3-urls-earthdata-cloud-data-access) 

[PODAAC Data Subscriber](https://github.com/podaac/data-subscriber/blob/main/README.md) – A Python-based command-line tool that supports spatial and temporal filtering. Though designed for PODAAC, it can be adapted for NSIDC and other DAACs.

All of these command line options are detailed in this help article: [Downloading Data from Earthdata Cloud to Your Local Computer Using the Command Line](https://nsidc.org/data/user-resources/help-center/downloading-data-earthdata-cloud-your-local-computer-using-command-line)