---
title: "Projections and Coordinate Systems"
author: Andy P. Barrett
---

## Overview

The purpose of this reference guide is to provide an introduction to
and background for map projections.  For a full treatment, please
consult @snyder_projections_ 

## What is a map projection?


## What is a datum?

Ellipsoid - the Earth is not a sphere but an oblate spheroid of revolution - discovered by Newton.
Confirmed by measurements of length of arc.

The geoid - the figure (shape) of the Earth if it were measured at mean sea level - involves gravity.  The geoid is an undulating surface that deviates from a well fitting ellipsoid by ~ 100 m.

Reference ellipsoid
defined by:
1. semi-major and semi-minor axes;
2. semi-major axis and flattening;
3. semi-major axis and eccentricity;

These are all related.

Newton flattening 1/~300.  Add WGS84 for current estimate.

A datum is a smooth mathematical surface that closely fits the mean sea-level surface - from @snyder

Earth centered datums - e.g. WGS84 - no local reference point.  The center of the Earth is the reference point.

$$
b = a(1 - f); f = 1-b/a
$$
$$
e^2 = 2f - f^2; \\
f = 1 - (1 - e^2)^{1/2}
$$


## What is a coordinate reference system?


## NSIDC coordinate reference systems


## How can I define a map projects of CRS in a data file?

### NetCDF and CF-Conventions

Include a link to NSIDC projection definitions


### GeoTIFF


## Geographic Coordinate Systems
A _Geographic Coordinate System_ is a spherical or ellipsoidal coordinate system with coordinates latitude $\phi$, longitude $\lambda$, and height $z$.  Latitude and Longitude are defined relative to a reference ellipsoid.  There are many reference ellipsoids, so a full definition of geographic coordinates requires a full specification of the coordinate reference system.  _Check!_ Most global datasets, GPS and satellites use the WGS84 ellipsoid.

Two levels of abstraction are required to define latitude and longitude.  First a model of the  surface of the Earth is required.  This model approximates mean sea level over the oceans and continues this surface under the continents.  The second step is to approximate the geoid with a mathematical definition of the surface of the geoid.  A simple solution is to use a sphere.  However, it is more accurate to use an Ellipsoid.

The latitude of a point on the reference ellipsoid is the angle formed
by the normal to the reference surface at the point of interest, and
the plane of the Equator or Equatorial Plane.  The Equatorial plane is
perpendicular to the Earths axis of rotation.
