---
title: "How to use earthaccess to examine data set metadata"
author: NSIDC Data Use and Education team
date: last-modified
execute:
  freeze: auto
---

## Problem
How can I use earthaccess to examine collection-level metadata e.g. for data sets (collections) returned in an `earthaccess.search_datasets()` query?

## Solution


```python
import earthaccess
```

```python 
results = earthaccess.search_datasets(
    keyword = 'snowex'
)
len(results)
```
127

```python
for r in results[:3]:
    long_name = r.get_umm('EntryTitle')
    short_name = r.get_umm('ShortName')
    description = r.get_umm('Abstract')
    doi = r.get_umm('DOI')
    print(long_name, short_name, description, doi, sep='\n')
    print( )
```
SnowEx23 Mar23 Snow Pit Measurements V001  
SNEX23_MAR23_SP  
The data set presents snow pit measurements collected during the NASA SnowEx March 2023 Intensive Observation Period (IOP) in Alaska, USA to use for calibration and validation with coincident airborne SWESARR and lidar measurements as part of the strategy focused on snow water equivalence (SWE) and snow depth (HS). In total, 170 snow pits were excavated between the five sites at locations representing a range of snow depth, vegetation, and topographic conditions. Three study areas represented boreal forest snow near Fairbanks, AK: Farmers Loop Creamers Field (FLCF), Caribou Poker Creek Research Watershed (CPCRW), and Bonanza Creek Experimental Forest (BCEF). Two study areas represented Arctic tundra snow: Arctic Coastal Plain (ACP) and Upper Kuparuk Toolik (UKT).  
{'DOI': '10.5067/SJZ90KNPKCYR'}

SnowEx21 Time Series Snow Pits V001  
SNEX21_TS_SP  
The data set is a time-series of snow pit measurements obtained by the SnowEx community during the 2021 field campaign. Between November 2020 and May 2021 data from 247 snow pits were collected at 24 unique sites distributed over 4 states (CO, ID, MT, UT) throughout the Western United States. Five of the unique sites had a single visit to establish baseline conditions, while the remaining 19 sites had 3 or more repeat visits throughout the season, with a median visit count of 11.5. On a weekly interval, a snow pit was dug approximately 1 m away from the previous week’s snow pit. Available measured parameters are: snow depth, snow temperature, snow density, stratigraphy, grain size, manual wetness, liquid water content (LWC), and snow water equivalent (SWE). Also available are photos of the field notes and snow pit sites.  
{'DOI': '10.5067/QIANJYJGRWOV'}

SnowEx20 Time Series Snow Pit Measurements V002  
SNEX20_TS_SP  
The data set is a time-series of snow pit measurements obtained by the SnowEx community during the 2020 campaign. Between October 2019 and May 2020, data were collected from 454 snow pits at 12 regional locations throughout California, Colorado, Idaho, New Mexico, and Utah, USA. At each of the locations, between 1 and 11 sites covering a range of conditions (terrains, snow depths, etc.) were chosen for weekly snow pit observations.  Also available are photos of the field notes and snow pit sites.  
{'DOI': '10.5067/KZ43HVLZV6G4'}


## Discussion

The earthaccess function `get_umm()` allows us to explore the results of a data set query by extracting various metadata elements from the [Unified Metadata Model (UMM)](https://nsidc.github.io/NSIDC-Data-Cookbook/reference-guides/collections-granules.html#nasas-metadata-backbone-cmr) records of data sets.  

Some useful metadata available through the `get_umm()` function:

- ShortName - abbreviated or short-hand data set name
- EntryTitle - full, long-form data set name including version
- Abstract - short description of a data set including information such as location, temporal range, and data collection methods.
- DOI - a Digital Object Identifier is a unique, permanent alphanumeric code assigned to digital objects—most commonly academic journal articles, books, and research datasets—to provide a persistent, actionable link to their location on the internet. Unlike URLs, which can change, a DOI remains stable over time. 
- SpatialExtent - geolocation information about the data set which can include latitude/longitude coordinates for the bounding box that encompasses the data
- ScienceKeywords - science terms associated with the relevant parameters contained in the data set 
- Version - data set version
- VersionDescription - description of updates included in most recent version
- UseConstraints - license text and citation instructions
- Platforms - provides satellite and aircraft platforms and sensors, or indicates ground-based observations and instruments 