---
title: "Projections and Coordinate Systems"
author: Andy P. Barrett
---

## Overview

This reference guide provides an introduction to coordinate reference
systems for geospatial data.  For a full treatment, please consult
@snyder_projections_

## Geospatial Data

Geospatial data and information is defined as data and information
associated with a location relative to the Earth.  It is also referred
to as geographic data and information, georeferenced data and
information, or geodata and geoinformation.  Geospatial data may be
vector data (points, line or polygons), raster or gridded data, or
geographic databases.  Locations of data relative to the Earth are
defined by a Coordinate Reference System (CRS).


## Data Models

Vector data, raster data and geographic databases are all way to
represent geospatial data.  Examples vector datasets are the locations
of capital cities defined by a latitude and longitude for each city.
The network of US interstate highways can be represented as a set of
line segments, where the end points of each line segment is a latitude
longitude pair.  Country boundaries can be represented as polygons
made up of line segments.  Points, line segments and polygons can all
be assigned values.  For example, if points represent the locations of
capital cities, value attributes of each point could be the name of
the city.  Other values suh as the population could also be assigned.
For the interstate highway data, line segments could have highway
number as a value, but also speed limite or average traffic flow.
Country polygons could have area, population, rainfall or any number
of values assiciated with it.  Once values are assigned to vector
data, the distingction between a geospatal database and vector data
begins to be blurred.  

Raster data is an rectangular array of points or areas that each have a location
and a set values associated with them.  Raster data can represent
values at grid intersections or as values for the area of grid cells.
For remote sensing data grid cells are called pixels.  A grid of temperatures or an
array of precipitation values or some remote sensing value.

## Coordinate Reference Systems

**C**oordinate **R**eference **S**ystems (CRS) define the position,
  scale and orientation of a coordinate system with respect to an
  object.  For geospatial data this object is the Earth.  A coordinate
  system is defined by a dimension, the number of axes.  For a
  geospatial coordinate system, the coordinates may be latitude and
  longitude, or x, y, z, which have 2 and 3 dimensions respectively.
  Each axis has name; the sequence of axes, the order in which axes
  are stated; the direction of the axis; and the units of the axis.  A
  coordinate syetem is related to the Earth by a datum, which defines
  the origin of the coordinate system relative to a model of the
  earth.

  Coordinate Reference Systems for geospatial data are *Geodetic
  Coordinate Reference Systems* and *Projected Coordinate Reference
  Systems*.  *Image Coordinate Reference Systems* and *Engineering
  Coordinate Reference Systems* relate raster or gridded data, and
  survey data to Geodetic and Projected Coordinate Reference Systems.   


## What is a map projection?

Projection parameters - depend on projection type.  But at the very
least require a datum or reference ellipsoid.  Geographic coordinates
that relate the projected surface to this sphere or ellipsoid.  This
defines the origin of the projected coordinates.  Definitions also
include false northings and false easting if the origin of the
projected coordinates is not at the center of the projection???.

## What is a datum?

### Notes on Datums and Coordinates Reference Systems from Iliffe and Lott (2008)

_Coordinate System_: A set of rules that define how coordinates are assigned to locations.  A coordinate system is defined by
a dimension (the number of axes), each axes has a coordinate associated with it.  Each axis of a coordinates system has the following attributes:
- the name or abbreviation of the axis (e.g. Latitude);
- the sequence number of the axis so that coordinate order is define (e.g. (x,y,z) or (z,y,x));
- the direction of the axis in which coordinates increment;
- the units of the axis.

_Datum_: A datum is the information that fixes a _coordinate system_ to an object (e.g. Earth).  A _Geodetic datum_ is a datum that defined the relationship of a coordinate system to an ellipsoidal model of Earth with the Geoid (I&L say real Earth).

The size and shape of the best fitting ellipsoid to the Earth is GRS 1980.

International Terrestrial Reference System (ITRS) describes a 3
dimensional cartesian coordinate system in which the direction of the
Earth's rotation axis and speed of rotation are defined.  These change
and the International Earth Rotation and Reference Systems Service
(IERS) monitors and predicts the Earth's rotation and the movement of
it's poles.  This information is essential to determine the position
of a satellite in a terrestrial (reference) system.

For a global datum, the prime meridian is defined and allows for the
movement of the poles (precession and nutation).  Note: the prime
meridian does not agree with the old Greenwich Observatory and may be
off by 102 m.  Greenwich prime meridian is defined by IERS.

The origin of the ITRS is the center of the Earth.

A _Coordinate Reference System_ is a coordinate system that has been
referenced to a datum - where datum in this sense if the full datum
realization (points of known coordinates has been marked as physical
monuments - needs further explanation).

The International Terrestrial Reference Frame (ITRF) is the
realization of the ITRS.  ITRF is the coordinates of the network of
[ground stations](https://itrf.ign.fr/en/network/map).  The ITRF
changes because of the motion of Earth's tectonic plates.  Station
coordinates are only valid for the epoch (January 1 of the year of
realization) of the realization (e.g. ITRF2008).  The reference frame
consists not only of station coordinates but also the velocity of the
stations.  Station coordinates can then be calculated for different
epochs.

Define epoch

WGS84 - the World Geodetic System of 1984 - is the reference for
positions determined through GPS.  US GPS satellites (distinct from
the Russia GLONASS, European Galilieo, and Chinese BeiDou satellite
navigation systems.  GPS positions start with the satellite
ephemerides (orbital positions) that are determined from a network of
ground monitoring stations maintained by the US military.  The
positions of these ground stations are changing.  WGS 84 is
maintained to be within a few centimeters of the current ITRF.  A
strict definition of WGS 84 has the form WGS 84 (GXXX) where XXX is
the GPS week number.  


Ellipsoid - the Earth is not a sphere but an oblate spheroid of revolution - discovered by Newton.
Confirmed by measurements of length of arc.

The geoid - the figure (shape) of the Earth if it were measured at mean sea level - involves gravity.  The geoid is an undulating surface that deviates from a well fitting ellipsoid by ~ 100 m.
) 
Reference ellipsoid
defined by:
1. semi-major and semi-minor axes;
2. semi-major axis and flattening;
3. semi-major axis and eccentricity;

These are all related.

Newton flattening 1/~300.  Add WGS84 for current estimate.

A datum is a smooth mathematical surface that closely fits the mean sea-level surface - from @snyder

Earth centered datums - e.g. WGS84 - no local reference point.  The center of the Earth is the reference point.

$$
b = a(1 - f); f = 1-b/a
$$
$$
e^2 = 2f - f^2; \\
f = 1 - (1 - e^2)^{1/2}
$$


## Geodetic versus Geographic latitude


## What is a coordinate reference system?


## NSIDC coordinate reference systems


## How can I define a map projects of CRS in a data file?

### NetCDF and CF-Conventions

Include a link to NSIDC projection definitions


### GeoTIFF


## Geographic Coordinate Systems
A _Geographic Coordinate System_ is a spherical or ellipsoidal coordinate system with coordinates latitude $\phi$, longitude $\lambda$, and height $z$.  Latitude and Longitude are defined relative to a reference ellipsoid.  There are many reference ellipsoids, so a full definition of geographic coordinates requires a full specification of the coordinate reference system.  _Check!_ Most global datasets, GPS and satellites use the WGS84 ellipsoid.

Two levels of abstraction are required to define latitude and longitude.  First a model of the  surface of the Earth is required.  This model approximates mean sea level over the oceans and continues this surface under the continents.  The second step is to approximate the geoid with a mathematical definition of the surface of the geoid.  A simple solution is to use a sphere.  However, it is more accurate to use an Ellipsoid.

The latitude of a point on the reference ellipsoid is the angle formed
by the normal to the reference surface at the point of interest, and
the plane of the Equator or Equatorial Plane.  The Equatorial plane is
perpendicular to the Earths axis of rotation.


## Standard terms for projection parameters

The OGC CRS WKT standard gives accepted names in Table F.3.  Several
terms are acceptable to describe latitude_of_origin,
longitude_of_origin.  There is no latitude_of_true_scale.  There is
also no mention of latitude_of_true_origin

https://docs.ogc.org/is/18-010r7/18-010r7.html#221

PROJ gives common parameter names here https://proj.org/usage/projections.html

Individual projections have specific parameters.

The stereographic projection is here https://proj.org/operations/projections/stere.html
The Lambert Azimuthal Equal Area, which is the basis for the EASE Grids, is here https://proj.org/operations/projections/laea.html

The CF-Conventions describe the parameters required for the grid_mapping variable.
Lambert Azimuthal Equal Area https://cfconventions.org/cf-conventions/cf-conventions.html#lambert-azimuthal-equal-area
Polar Stereographic https://cfconventions.org/cf-conventions/cf-conventions.html#polar-stereographic

