---
title: "Video Resources"
---

At NSIDC we make learning content in many mediums, including video. You can find links to the various topics we have covered, categorized by either "short-form" (less than 30 minutes long) or "long-form" (videos longer than half an hour). 

---

## Short-form videos

| Title | Description |
|----------|---------------|
|[**Using the earthaccess Python Library to Stream Data**](https://www.earthdata.nasa.gov/events/using-earthaccess-python-library-stream-data) | This short webinar demonstrates how to use the earthaccess Python library to stream NASA data directly to memory, skipping the download. The presenter explains the difference between downloading data and streaming data, and then works through an example using the NASA MERRA-2 reanalysis product.
|[**Subsetting and Reformatting Data from the NASA Earthdata Cloud Using harmony-py**](https://www.earthdata.nasa.gov/learn/webinars/subsetting-reformatting-data-from-nasa-earthdata-cloud-using-harmony-py) | This short, informative walkthrough on subsetting and reformatting data from the NASA Earthdata Cloud using harmony-py helps users understand how the harmony-py Python library can help them customize the data they request from the NASA Earthdata Cloud. The presenter introduces Harmony services and demonstrates how to explore and implement available subsetting and reformatting services using an example dataset within a Jupyter notebook environment.
|[**Downloading Data from the NASA Earthdata Cloud Using the earthaccess Python Library**](https://www.earthdata.nasa.gov/learn/webinars/downloading-data-from-nasa-earthdata-cloud-using-earthaccess-python-library) | This NASA Earthdata webinar short demonstrates the basics of using earthaccess to download data from the NASA Earthdata Cloud.

## Long-form videos

| Title | Description |
|----------|---------------|
|[**Laser Altimetry Applications for a Changing World: Measuring Snow Depth with ICESat-2**](https://www.earthdata.nasa.gov/learn/webinars/laser-altimetry-applications-changing-world-measuring-snow-depth-icesat-2) | In this webinar, speakers from NSIDC, NASA's Goddard Space Flight Center, and NASA's Langley Research Center introduce the ICESat-2 Global Geolocated Photons product (ATL03) and present an overview of two snow depth estimation methods: the pathlength method and the snow on/off method. Viewers can explore data discovery and access through live demonstrations using Jupyter Notebooks and NASA Earthdata Search.
|[**Laser Altimetry Applications for a Changing World: Working with ICESat-2 Inland Surface Water Data**](https://www.earthdata.nasa.gov/learn/webinars/laser-altimetry-applications-changing-world-working-icesat-2-inland-surface-water) | In this webinar, speakers from NASA's Goddard Space Flight Center and the University of New Hampshire (UNH) will introduce the ICESat-2 Inland Surface Water product (ATL13) and Gridded Inland Surface Water product, (ATL22), as well as their associated application areas for water resources decision support. In addition, a data discovery and data access demonstration will showcase icepyx, a shared software library of resources including code, tutorials, and use-cases/examples that simplify the process of querying, obtaining, analyzing, and manipulating ICESat-2 datasets to enable scientific discovery.
|[**Laser Altimetry Applications for a Changing World: Working with ICESat-2 Sea Ice Data**](https://www.earthdata.nasa.gov/learn/webinars/laser-altimetry-applications-changing-world-working-icesat-2-sea-ice-data) | In this webinar, we provide an overview of the reference ICESat-2 sea ice data products. These include the along-track sea ice height and freeboard products (ATL07 and ATL10), as well as the derived gridded products ATL20 and ATL21. We demonstrate earthaccess, a Python package to search for and access NASA data, including ICESat-2 datasets, both in the cloud and from your local machine. Lastly, we present specific data use cases, including the derivation of sea ice thickness and applications in sea ice and climate modeling.
|[**Laser Altimetry Applications for a Changing World: Working with ICESat-2 Bathymetry Data**](https://www.earthdata.nasa.gov/learn/webinars/laser-altimetry-applications-changing-world-working-icesat-2-bathymetry-data) | In this webinar, we cover a new global ICESat-2 bathymetric data product, ATL24, including results of an ATL24 accuracy test. We then present use cases, including training models for extracting bathymetry from multispectral imagery and identifying hazards to marine navigation. We also demonstrate a public web application programming interface (API) for processing ICESat-2 data in the cloud.
|[**Laser Altimetry Applications for a Changing World: Working with ICESat-2 Land and Vegetation Height Data**](https://www.earthdata.nasa.gov/learn/webinars/laser-altimetry-applications-changing-world-working-icesat-2-land-vegetation-height) | In this webinar, speakers from the NASA ICESat-2 Science and Application teams and Goddard Space Flight Center introduce the ICESat-2 Land and Vegetation Height data product and provide an overview of a derived continental scale canopy model. In addition, the webinar showcases the SlideRule Earth web service, demonstrating high-performance, on-demand science data processing of ICESat-2 and other relevant geospatial data.
|[**Laser Altimetry Applications for a Changing World: Explore ICESat-2 Data**](https://www.earthdata.nasa.gov/learn/webinars/laser-altimetry-applications-changing-world-explore-icesat-2-data) | This webinar is the first in a series to introduce the ICESat-2 platform. Topics include an overview of the platform, data products and data discovery, and data access tools. A demonstration showcases the advanced data discovery and data visualization features of OpenAltimetry—a web-based application that provides on-demand surface elevation profiles.
