on:
  workflow_dispatch:
  push:
    branches: [main]

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup micromamba
        if: github.event.action != 'closed'
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: conda-lock.yml
          environment-name: ci
          init-shell: bash
          cache-environment: true
      
      - name: Render Quarto Project using mamba environment
        if: github.event.action != 'closed'
        shell: micromamba-shell {0}
        run: quarto render
      
      - name: Deploy to GitHub Pages
        if: github.event.action != 'closed'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          keep_files: true
 
